import React from 'react'

const faqs = [
    {
        title: "How long is this going to take?",
        text: "It depends… on YOU.  In general, it takes 1 to 2 times a week for 4 to 6 weeks to see a change in symptoms.  If not, we will re-evaluate.  Of course, every individual is unique.  More often it’s like peeling away the layers of an onion.  We release restrictions layer by layer until we get to the core issue that’s been holding all the others in place."
    },
    {
        title: "How do I know the cause of my pain?",
        text: "As you become more connected and aware, you will know.  The cause of pain is not always what you think.  It’s often generated by the unconscious.  Consciousness is the goal."
    },
    {
        title: "How does Unified Therapy™ differ from other healing modalities?",
        text: "While a lot of therapies just deal with the biomechanical or mental aspects of a condition, Unified Therapy™ is the only known toxic stress, anxiety, and pain therapy that allows active participation in the healing process.  It is the new model for addressing all the components of neuromuscular pain.  All components must be addressed and unified for long term healing to take place."
    },
    {
        title: "Do you think Unified Therapy™ could help with psychosomatic issues, as I have pains in my body that I think may be really related to my emotions?",
        text: "Unified Therapy™ is ideal for psychosomatic issues such as pains in the body that may be related to emotions.  If you are suffering from syndromes or symptoms that cannot be explained medically, then Unified Therapy™ is for you."
    },
    {
        title: "What do I need to do for complete care? Am I going to relapse?",
        text: ["It has been shown that by-weekly or monthly sessions can dramatically improve your state of health, slow down degeneration and release the most important attribute to disease and illness – TOXIC STRESS!",<br/>,<br/>,"Toxic Stress (relationships, family, job) is one of the major causes of illness and death.  Science says and has proven that most disease comes from abnormalities in stress physiology that starts early.  Don’t wait until you are in pain or get overwhelmed to schedule an appointment."]
    }
]

export default faqs